<?php

function sco_block_partenaires_block_info() {
	$blocks['liste_partenaires'] = array(
    // The name that will appear in the block list.
    'info' => t('Bloc liste partenaires'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}



function sco_block_partenaires_block_view($delta="") {
	switch($delta) {
		case "liste_partenaires":
			$block["subject"]=t("Liste des partenaires");
			if(user_access("access content")) {
				$items="ddd";

				if(empty($items)) $block["content"]=t('no data');
				else {
					$block["content"]=theme("sco_block_partenaires",array("items"=>$items));
				}

			}
			return $block;
	}
}


function sco_block_partenaires_theme() {
	return array(
		"sco_block_partenaires" => array(
			'template' => 'sco_block_partenaires',
			'arguments' => array(),
		),
	);
}

